### ISSUE TITLE
WebServer error

### ISSUE THREAD

**Issue by NFellGill** [TheBastionBot/Tesseract#32]
Hello. I saw that Tesseract have a WebServer (Tesseract.WebServer). 

So I wanted to test with this code:

```javascript
const Tesseract = require('tesseract');

const test = new Tesseract.WebServer(Manager);
test.start();
```

But its returns me this error :

```shell
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:8377
    at listenOnMasterHandle (net.js:1373:18)
    at shared (internal/cluster/child.js:123:3)
    at Worker.<anonymous> (internal/cluster/child.js:94:7)
    at process.onInternalMessage (internal/cluster/utils.js:43:8)
    at process.emit (events.js:228:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Server instance at:
    at listenOnMasterHandle (net.js:1374:21)
    at shared (internal/cluster/child.js:123:3)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 8377
}
```

**Comment by k3rn31p4nic** [comment]
This project is only being used by Bastion internally, so there's no support for this.
